package com.lanou.dao;

import com.lanou.bean.Emp;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface EmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbggenerated Tue Apr 16 14:33:39 CST 2019
     */
    @Delete({
        "delete from emp",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbggenerated Tue Apr 16 14:33:39 CST 2019
     */
    @Insert({
        "insert into emp (id, name, ",
        "sex, job, salary, ",
        "hiredate, deptno)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{sex,jdbcType=CHAR}, #{job,jdbcType=VARCHAR}, #{salary,jdbcType=DECIMAL}, ",
        "#{hiredate,jdbcType=DATE}, #{deptno,jdbcType=INTEGER})"
    })
    int insert(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbggenerated Tue Apr 16 14:33:39 CST 2019
     */
    @InsertProvider(type=EmpSqlProvider.class, method="insertSelective")
    int insertSelective(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbggenerated Tue Apr 16 14:33:39 CST 2019
     */
    @Select({
        "select",
        "id, name, sex, job, salary, hiredate, deptno",
        "from emp",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="sex", property="sex", jdbcType=JdbcType.CHAR),
        @Result(column="job", property="job", jdbcType=JdbcType.VARCHAR),
        @Result(column="salary", property="salary", jdbcType=JdbcType.DECIMAL),
        @Result(column="hiredate", property="hiredate", jdbcType=JdbcType.DATE),
        @Result(column="deptno", property="deptno", jdbcType=JdbcType.INTEGER)
    })
    Emp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbggenerated Tue Apr 16 14:33:39 CST 2019
     */
    @UpdateProvider(type=EmpSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbggenerated Tue Apr 16 14:33:39 CST 2019
     */
    @Update({
        "update emp",
        "set name = #{name,jdbcType=VARCHAR},",
          "sex = #{sex,jdbcType=CHAR},",
          "job = #{job,jdbcType=VARCHAR},",
          "salary = #{salary,jdbcType=DECIMAL},",
          "hiredate = #{hiredate,jdbcType=DATE},",
          "deptno = #{deptno,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Emp record);
}