package com.lanou.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.lanou.bean.Emp;

public class EmpSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbggenerated Tue Apr 16 14:33:39 CST 2019
     */
    public String insertSelective(Emp record) {
        BEGIN();
        INSERT_INTO("emp");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getName() != null) {
            VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        if (record.getSex() != null) {
            VALUES("sex", "#{sex,jdbcType=CHAR}");
        }
        
        if (record.getJob() != null) {
            VALUES("job", "#{job,jdbcType=VARCHAR}");
        }
        
        if (record.getSalary() != null) {
            VALUES("salary", "#{salary,jdbcType=DECIMAL}");
        }
        
        if (record.getHiredate() != null) {
            VALUES("hiredate", "#{hiredate,jdbcType=DATE}");
        }
        
        if (record.getDeptno() != null) {
            VALUES("deptno", "#{deptno,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbggenerated Tue Apr 16 14:33:39 CST 2019
     */
    public String updateByPrimaryKeySelective(Emp record) {
        BEGIN();
        UPDATE("emp");
        
        if (record.getName() != null) {
            SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        if (record.getSex() != null) {
            SET("sex = #{sex,jdbcType=CHAR}");
        }
        
        if (record.getJob() != null) {
            SET("job = #{job,jdbcType=VARCHAR}");
        }
        
        if (record.getSalary() != null) {
            SET("salary = #{salary,jdbcType=DECIMAL}");
        }
        
        if (record.getHiredate() != null) {
            SET("hiredate = #{hiredate,jdbcType=DATE}");
        }
        
        if (record.getDeptno() != null) {
            SET("deptno = #{deptno,jdbcType=INTEGER}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}